[package]
name = "commands"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-query = { version = "0", features = ["derive"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "postgres" ] }
